name = "ClimFlowsPlots"
uuid = "dd0979db-5334-4d13-8d2e-fa88a4f47f12"
authors = ["The ClimFlows contributors"]
version = "0.2.0"

[deps]
BoundingSphere = "747eb165-47b8-53f2-ad32-9704a7dfc50a"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
Makie = "0.20, 0.21"
GeoMakie = "0.6, 0.7"
BoundingSphere = "0.2"
ColorSchemes = "1,2,3"
GeometryBasics = "0.4"
LightGraphs = "1"
Metis = "1"
StaticArrays = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[targets]
test = ["Test"]
